### ISSUE TITLE
Missing Manager/Coach Profiles

### ISSUE THREAD

**Issue by realonbebeto** [dcaribou/transfermarkt-datasets#159]
Hello, 
While working with data I  noticed that profiles of managers/coach are missing is it possible to have that in the next version?

**Comment by dcaribou** [comment]
Hi @realonbebeto, thanks for reaching out.

Club manager's names are available in the `games` and `club_games` assets. Do you mean you found them missing in those files?

**Comment by realonbebeto** [comment]
Thanks for the prompt response but some clubs are missing manager names.

**Comment by dcaribou** [comment]
Can you provide some examples?
