### ISSUE TITLE
poetry.lock is not consistent with pyproject.toml

### ISSUE THREAD

**Issue by justbennet** [dcaribou/transfermarkt-datasets#233]
I just installed poetry using `install.python-poetry.org`,
```
$ poetry --version
Poetry (version 1.6.1)
```
and I just cloned `transfermarkt-datasets`
```
$ git clone https://github.com/dcaribou/transfermarkt-datasets.git
Cloning into 'transfermarkt-datasets'...
remote: Enumerating objects: 2661, done.
remote: Counting objects: 100% (629/629), done.
remote: Compressing objects: 100% (433/433), done.
remote: Total 2661 (delta 294), reused 458 (delta 192), pack-reused 2032
Receiving objects: 100% (2661/2661), 3.71 MiB | 12.94 MiB/s, done.
Resolving deltas: 100% (1236/1236), done.
```
So, I change to `transfermarkt-datasets` and I run
```
$ poetry install
Creating virtualenv transfermarkt-datasets-_V5wJHcv-py3.10 in /home/bennet/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```
Should I run `poetry lock`?  With or without `--no-update`?

Is this something that should be fixed 'at source'?

Thanks in advance for any guidance to the beginner asking!

**Comment by dcaribou** [comment]
Hi @justbennet, thanks for raising this.

I can see the same warning coming up in [the CI logs](https://github.com/dcaribou/transfermarkt-datasets/actions/runs/6466373292/job/17554280568). I'll have a look.

This should just be a warning though, and the installation should proceed anyways right?

**Comment by justbennet** [comment]
Yes, correct; it does show up as a warning and the installation seems to go through.  The issued warning was fairly dire, so I wanted to make sure you knew about it.

I ran `poetry lock`, and there was a fair amount of activity as a consequence.  Presumably, this was trying to reconcile dependency version differences, and I don't know if any of those might introduce an incompatibility.

I also don't understand what effect adding the `--no-update` would have.  Would that result in just reporting differences?

Thanks for looking into this!  Very much appreciated.

**Comment by dcaribou** [comment]
Closing since I no longer see the warning in the build logs ([example](https://github.com/dcaribou/transfermarkt-datasets/actions/runs/7159067617/job/19491937329))
