### ISSUE TITLE
Date of birth not retrieved 

### ISSUE THREAD

**Issue by paolocupini** [dcaribou/transfermarkt-datasets#264]
I noticed that **date_of_birth** attribute is not present for players whose **last_season** = "2023".

**Comment by dcaribou** [comment]
Hi @paolocupini,
I think it might be related to this https://github.com/dcaribou/transfermarkt-scraper/pull/80.
Let me bump the scraper version and see if this solves the issue.

**Comment by dcaribou** [comment]
Yep, that was the problem.
It should get resolved after I merge the related PR. The change might take a few minutes to propagate to the data frontends.
