### ISSUE TITLE
game_lineups not updated anymore

### ISSUE THREAD

**Issue by rakete1** [dcaribou/transfermarkt-datasets#286]
Hi! Thank you for the great data set. What a clean work!!
However I might found an issue with the "game_lineups". The latest game_id is '4080529' which is a game from May 2023.
I expected to find the recent lineups in this file as well.
Best Regards
Ralph

**Comment by dcaribou** [comment]
Re-opened in https://github.com/dcaribou/transfermarkt-datasets/issues/290.

**Comment by dcaribou** [comment]
It seem like that game's ([2244385](https://www.transfermarkt.co.uk/rcd-mallorca_rcd-espanyol-barcelona/aufstellung/spielbericht/2244385)) lineup should be there, you are right @Kokolaie.
I can't tell why it isn't though. Most likely the last time lineups where scraped the lineups where not there, but I can't tell for sure.

The lineups scraper is broken atm, so unfortunately i can't be refreshed until this is resolved https://github.com/dcaribou/transfermarkt-scraper/issues/88.

**Comment by Kokolaie** [comment]
Thank you very much for your answer.
There are several games without line_ups.
I wanted to scrap transfermarkt with selenium, but initially, i improved my skills on an other website on tennis datas.

I have an extra question: why the club values are missing?

Regards,
Kokolaie







Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : David ***@***.***>
Date : 11/05/2024 12:09 (GMT+01:00)
À : dcaribou/transfermarkt-datasets ***@***.***>
Cc : Kokolaie ***@***.***>, Mention ***@***.***>
Objet : Re: [dcaribou/transfermarkt-datasets] game_lineups not updated anymore (Issue #286)


It seem like that game's (2244385<https://www.transfermarkt.co.uk/rcd-mallorca_rcd-espanyol-barcelona/aufstellung/spielbericht/2244385>) lineup should be there, you are right @Kokolaie<https://github.com/Kokolaie>.
I can't tell why it isn't though. Most likely the last time lineups where scraped the lineups where not there, but I can't tell for sure.

The lineups scraper is broken atm, so unfortunately i can't be refreshed until this is resolved dcaribou/transfermarkt-scraper#88<https://github.com/dcaribou/transfermarkt-scraper/issues/88>.

**Comment by dcaribou** [comment]
> I have an extra question: why the club values are missing?

Which club values?

**Comment by Kokolaie** [comment]
the total marker value in clubs.csv

**Comment by dcaribou** [comment]
> the "total market value" in clubs.csv
Or to calculate it may be we justahave to add all players values?

Since this is unrelated to this issue, let's move this question somewhere else.
Please, check [this discussion ](https://github.com/dcaribou/transfermarkt-datasets/discussions/164)and that is not clarifying enough let's follow up there.
