### ISSUE TITLE
Error when cloning project (streamlit)

### ISSUE THREAD

**Issue by BCinformational** [dcaribou/transfermarkt-datasets#291]
error: invalid path 'streamlit/pages/02_🔎_app:_explore_dataset.py'
fatal: unable to checkout working tree

This occurs when trying to clone the project in both Visual Studio Code and GitHub Desktop.

**Comment by dcaribou** [comment]
This was reported in the past from a windows user [here](https://github.com/dcaribou/transfermarkt-datasets/issues/107).
Could you try the suggestions there and follow up in that other issue if you have any trouble?
