### ISSUE TITLE
Europa Conference League Games Missing

### ISSUE THREAD

**Issue by bcunno95** [dcaribou/transfermarkt-datasets#304]
Hi, great dataset thanks for pulling this together! Europa Conference League qualifying games are present in the dataset but not Europa Conference League games. You can also see they are missing in the exported JSON file. Hopefully there an easy fix for this?

**Comment by dcaribou** [comment]
Hi @bcunno95.
Thanks for raising this. You're right indeed, Europa Conference League was missing.

[I've added it](https://github.com/dcaribou/transfermarkt-datasets/commit/67f4627088be68313773c2245f85aff849ee21da) as a new competition. Your should start seeing the games from now on.
